services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data 
    depends_on:
      - auth_server
    environment:
      LOG_LEVEL: INFO
      database_url: sqlite+aiosqlite:///data/thingy91.db
    networks:
      - shared_network

  auth_server:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8001:8001"
    environment:
      LOG_LEVEL: INFO
    networks:
      - shared_network

networks:
  shared_network:
    external: true
