services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - auth_server
    environment:
      LOG_LEVEL: INFO

  auth_server:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8001:8001"
    environment:
      LOG_LEVEL: INFO
